name: timetracking
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  get_it: ^7.2.0 
  flutter_animate: ^1.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  flutter_colorpicker: ^1.0.3
  permission_handler: ^10.2.0
  url_launcher: ^6.1.8
  equatable: ^2.0.5
  csv: ^5.0.1
  fluttertoast: ^8.0.9
  intl: ^0.18.0
  flex_color_scheme: ^6.1.2


  
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.2
  lints: ^2.0.1
  flutter_native_splash: ^2.2.16
  
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png





flutter:

  
  
  
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  
  fonts:
   
    - family: IconFont
      fonts:
        - asset: assets/fonts/IconFont.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
